### ISSUE TITLE
Add Default Queries

### ISSUE THREAD

**Issue by situx** [sparqlunicorn/sparqlunicornGoesGIS#2]
It would be a good idea to add default queries to the plugin.
This requires:

1. A query to find out some/all geospatial concepts of a triple store, sth. like this:
SELECT DISTINCT ?class WHERE{
?item               wdt:P31        ?class. 
?item               wdt:P625         ?coord.}
Could be a performance issue though.

2. A query to select some/all direct properties of individuals of the class in a certain area as a default query.
Input: Concept (from previous query), boundingbox or concept like country, language
select ?rel ?relLabel WHERE { 
?con wdt:P31 CONCEPT .
?con wdt:P625 ?coord . 
?con wdt:P17 AREA .  (or Boundingbox query part) 
?con ?rel ?val . 
SERVICE wikibase:label { bd:serviceParam wikibase:language LANGUAGE . }  }
GROUP BY ?rel ?relLabel 
ORDER BY ?relLabel

Ideally, a user could choose or search a list of geospatial concepts of the respective triple store and with the provision of boundingbox or country get a GeoJSON layer into QGIS.
This would increase the accessibility of the plugin to users who are not able to write SPARQL.

**Comment by florianthiery** [comment]
Yes, we should implement sth like that. In the spirit of the **SPARQLing Unicorn**
