### ISSUE TITLE
Content area of dialog box cannot be enlarged

### ISSUE THREAD

**Issue by Msch0150** [sparqlunicorn/sparqlunicornGoesGIS#30]
sparqlunicorn-0.13.1, QGIS 3.18.3-Zürich

It is possible to modify the size of the main dialog box "SPARQLing Unicorn QGIS Plugin" but the the content area inside the box does not change its size.

So increasing the box will just add emtpy space to the right and bottom.

Background: I am using a 4K display and I increased the scale of the text in the Windows display configuration. This increased text does not fit into the text fields of the sparqlunicorn by default. So I want to enlarge the dialog box so that the text can fit into the fields.

**Comment by situx** [comment]
Thank you for this bug report. I will look into it!

**Comment by situx** [comment]
We will fix this in the upcoming release 0.14. The master branch of this repository already contains updated ui files with dynamic layouts. Thanks for reporting

**Comment by situx** [comment]
Closing since it was fixed in version 0.14

**Comment by Msch0150** [comment]
Works like a charm.
Thanks.
