### ISSUE TITLE
List on Wikidata Tools?

### ISSUE THREAD

**Issue by bellerophons-pegasus** [sparqlunicorn/sparqlunicornGoesGIS#34]
The QGIS plugin would be a very nice candidate to list on the Wikidata tools page: https://www.wikidata.org/wiki/Wikidata:Tools

**Comment by situx** [comment]
Sure, if you want to add it go ahead or do we as the authors need to do that?

**Comment by phopfgartner** [comment]
Added to https://www.wikidata.org/wiki/Wikidata:Tools/Visualize_data

**Comment by TallTed** [comment]
More specifically -- 
https://www.wikidata.org/wiki/Wikidata:Tools/Visualize_data#SPARQLing_Unicorn_QGIS_Plugin

**Comment by situx** [comment]
Thanks @phopfgartner @TallTed closing here...
