### ISSUE TITLE
SPARQL Abfrage FactGrid fehlerhaft

### ISSUE THREAD

**Issue by florianthiery** [sparqlunicorn/sparqlunicornGoesGIS#38]
Bei Auswahl von FactGrid und Q Idetifiern fasst das Autovervollständigen nicht und bei Query resultiert ein Fehler.

**Comment by situx** [comment]
Fixed in [80bd9d5](https://github.com/sparqlunicorn/sparqlunicornGoesGIS/commit/80bd9d5a22f1eef83db236416c7bc13a8871fee6)
