### ISSUE TITLE
rdflib error

### ISSUE THREAD

**Issue by florianthiery** [sparqlunicorn/sparqlunicornGoesGIS#5]
see https://github.com/RDFLib/rdflib/pull/945

**Comment by florianthiery** [comment]
Windows

C:\Program Files\QGIS 3.8\apps\Python37\Lib\site-packages\rdflib\__init__.py

**Comment by florianthiery** [comment]
line 79: if not hasattr(__main__, '__file__') and sys.stdout!=None and sys.stderr.isatty():

**Comment by situx** [comment]
We fixed this error by including the dependencies of our plugin in the release beginning from version 0.10
